
POST http://localhost:1337/catalog/excel/bugs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IklUVVN0dWRlbnQiLCJzdWIiOiJJVFVTdHVkZW50IiwianRpIjoiNDE5ZjkyNjUiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDoyMDM2OSIsImh0dHBzOi8vbG9jYWxob3N0OjAiLCJodHRwOi8vbG9jYWxob3N0OjEzMzciXSwibmJmIjoxNjk2NDM3NTE4LCJleHAiOjE3MDQzODYzMTgsImlhdCI6MTY5NjQzNzUxOSwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.G8oL6YdlShl1MvwAhvkAt16d3X-_usnESZDh6E3kbsM


{
  "narrative": "Dogs make me sneeze",
  "description": "A different Description"
}


### Get the thing

GET 	http://localhost:1337/catalog/excel/bugs/a-different-description
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IklUVVN0dWRlbnQiLCJzdWIiOiJJVFVTdHVkZW50IiwianRpIjoiNDE5ZjkyNjUiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDoyMDM2OSIsImh0dHBzOi8vbG9jYWxob3N0OjAiLCJodHRwOi8vbG9jYWxob3N0OjEzMzciXSwibmJmIjoxNjk2NDM3NTE4LCJleHAiOjE3MDQzODYzMTgsImlhdCI6MTY5NjQzNzUxOSwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.G8oL6YdlShl1MvwAhvkAt16d3X-_usnESZDh6E3kbsM


### get all bugs for software
GET 	http://localhost:1337/catalog/excel/bugs/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6IklUVVN0dWRlbnQiLCJzdWIiOiJJVFVTdHVkZW50IiwianRpIjoiNDE5ZjkyNjUiLCJhdWQiOlsiaHR0cDovL2xvY2FsaG9zdDoyMDM2OSIsImh0dHBzOi8vbG9jYWxob3N0OjAiLCJodHRwOi8vbG9jYWxob3N0OjEzMzciXSwibmJmIjoxNjk2NDM3NTE4LCJleHAiOjE3MDQzODYzMTgsImlhdCI6MTY5NjQzNzUxOSwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.G8oL6YdlShl1MvwAhvkAt16d3X-_usnESZDh6E3kbsM


